import type { Metadata } from "next";
import { Inter, Fraunces } from "next/font/google";
import "./globals.css";
import Navbar from "./nav/Navbar";
import { cn } from "@/lib/utils";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const fraunces = Fraunces({ subsets: ["latin"], variable: "--font-frunces" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${inter.className} font-['Fraunces']`}>
        <div
          className={cn(
            "grid grid-cols-[0px_1fr] md:grid-cols-[0px_1fr] h-screen bg-background",
            inter.variable,
            fraunces.variable
          )}
        >
          <SessionProvider session={session}>
            <Navbar />
            {children}
          </SessionProvider>
        </div>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        </ThemeProvider> */}
        <Toaster />
      </body>
    </html>
  );
}
